name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-file: ci/environment.yml
        environment-name: ditto-ci
        cache-environment: true
        cache-downloads: true

    - name: Install dependencies
      shell: micromamba-shell {0}
      run: |
        export PYTHIA_ROOT="${CONDA_PREFIX}"
        make install JOBS=2

    - name: Run check
      shell: micromamba-shell {0}
      run: |
        export PYTHIA_ROOT="${CONDA_PREFIX}"
        make test
